# This workflow runs all workflows to build and test the code on various Linux
# flavors, as well as on MacOS and Windows, on a scheduled basis, on merge into
# the 'develop' or 'release*' branches, or when requested manually. Upon pushes
# to the develop branch it also uploads the libxrpl recipe to the Conan remote.
name: Trigger

on:
  push:
    branches:
      - legleux/linux_packages
      - develop
      - release
      - master
    paths:
      # These paths are unique to `on-trigger.yml`.
      - ".github/workflows/on-trigger.yml"

      # Keep the paths below in sync with those in `on-pr.yml`.
      - ".github/actions/build-deps/**"
      - ".github/actions/build-test/**"
      - ".github/actions/generate-version/**"
      - ".github/actions/setup-conan/**"
      - ".github/scripts/strategy-matrix/**"
      - ".github/workflows/reusable-build.yml"
      - ".github/workflows/reusable-build-test-config.yml"
      - ".github/workflows/reusable-build-test.yml"
      - ".github/workflows/reusable-build-pkg.yml"
      - ".github/workflows/reusable-pkg.yml"
      - ".github/workflows/reusable-package.yml"
      - ".github/workflows/reusable-strategy-matrix.yml"
      - ".github/workflows/reusable-test.yml"
      - ".github/workflows/reusable-upload-recipe.yml"
      - ".codecov.yml"
      - "cmake/**"
      - "conan/**"
      - "external/**"
      - "include/**"
      - "pkgs/**"
      - "src/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "conanfile.py"
      - "conan.lock"

  # Run at 06:32 UTC on every day of the week from Monday through Friday. This
  # will force all dependencies to be rebuilt, which is useful to verify that
  # all dependencies can be built successfully. Only the dependencies that
  # are actually missing from the remote will be uploaded.
  schedule:
    - cron: "32 6 * * 1-5"

  # Run when manually triggered via the GitHub UI or API.
  workflow_dispatch:

concurrency:
  # When a PR is merged into the develop branch it will be assigned a unique
  # group identifier, so execution will continue even if another PR is merged
  # while it is still running. In all other cases the group identifier is shared
  # per branch, so that any in-progress runs are cancelled when a new commit is
  # pushed.
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' && github.sha || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  # check-missing-commits:
  #   if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && contains(fromJSON('["develop", "release"]'), github.ref_name) }}
  #   uses: ./.github/workflows/reusable-check-missing-commits.yml

  # build-test:
  #   uses: ./.github/workflows/reusable-build-test.yml
  #   strategy:
  #     matrix:
  #       os: [linux, macos, windows]
  #   with:
  #     os: ${{ matrix.os }}
  #     strategy_matrix: ${{ github.event_name == 'schedule' && 'all' || 'minimal' }}
  #   secrets:
  #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-package:
    name: Build ${{ matrix.pkg_type }} ${{ matrix.arch }} packages
    uses: ./.github/workflows/reusable-build-pkg.yml
    secrets: inherit
    strategy:
      fail-fast: ${{ github.event_name == 'merge_group' }}
      matrix:
        # pkg_type: [rpm]
        pkg_type: [deb, rpm]
        arch: [amd64]
        # arch: [amd64, arm64]
    with:
      pkg_type: ${{ matrix.pkg_type }}
      arch: ${{ matrix.arch }}
