# This workflow builds and tests the binary for various configurations.
name: Build and test

# This workflow can only be triggered by other workflows. Note that the
# workflow_call event does not support the 'choice' input type, see
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#onworkflow_callinputsinput_idtype,
# so we use 'string' instead.
on:
  workflow_call:
    inputs:
      platform:
        description: "The platform to generate the strategy matrix for ('linux', 'macos', 'windows'). If not provided all platforms are used."
        required: false
        type: string
      trigger:
        description: "The trigger that caused the workflow to run ('commit', 'label', 'merge', 'schedule')."
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        description: "The Codecov token to use for uploading coverage reports."
        required: true

jobs:
  # Generate the strategy matrix to be used by the following job.
  generate-matrix:
    uses: ./.github/workflows/reusable-strategy-matrix.yml
    with:
      platform: ${{ inputs.platform }}
      trigger: ${{ inputs.trigger }}

  # Build and test the binary for each configuration.
  build-test-config:
    needs:
      - generate-matrix
    uses: ./.github/workflows/reusable-build-test-config.yml
    strategy:
      fail-fast: ${{ github.event_name == 'merge_group' }}
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      max-parallel: 10
    with:
      build_type: ${{ matrix.build_type }}
      cmake_args: ${{ matrix.cmake_args }}
      cmake_target: ${{ matrix.cmake_target }}
      enable_tests: ${{ matrix.enable_tests }}
      enable_package: ${{ matrix.enable_package }}
      enable_image: ${{ matrix.enable_image }}
      runs_on: ${{ toJson(matrix.runs_on) }}
      image: ${{ matrix.image }}
      config_name: ${{ matrix.config_name }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
