on:
  workflow_call:
    inputs:
      pkg_type:
        required: false
        type: string
      arch:
        required: false
        type: string
    # secrets:
    #   GPG_KEY_B64:
    #     description: "The gpg key to sign packages."
    #     required: true
    #   GPG_KEY_PASS_B64:
    #     description: "The gpg key passphrase."
    #     required: true
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build ${{ inputs.pkg_type }} ${{ inputs.arch }} package
    runs-on: heavy${{ inputs.arch == 'arm64' && '-arm64' || '' }}
    container: ghcr.io/xrplf/ci/${{ inputs.pkg_type == 'rpm' && 'rhel-9' || 'ubuntu-jammy' }}:gcc-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Build packages
        run: |
          ./pkgs/build.sh
          cat build_vars >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.pkg_type }}-${{ inputs.arch }}
          path: |
            *.deb
            *.ddeb
          if-no-files-found: error
        if: inputs.pkg_type == 'deb'

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.pkg_type }}-${{ inputs.arch }}
          path: "*${{ inputs.arch }}.${{ inputs.pkg_type }}"
          if-no-files-found: error
        if: inputs.pkg_type == 'rpm'

  test:
    name: Test ${{ inputs.pkg_type }} ${{ inputs.arch }} package
    needs: build
    runs-on: heavy${{ inputs.arch == 'arm64' && '-arm64' || '' }}
    container: ghcr.io/xrplf/ci/${{ inputs.pkg_type == 'rpm' && 'rhel-9' || 'ubuntu-jammy' }}:gcc-12
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.pkg_type }}-${{ inputs.arch }}
      - name: Running tests
        run: echo "Running tests..."

  sign:
    name: Sign ${{ inputs.pkg_type }} ${{ inputs.arch }} package
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:python3.13-bookworm-slim

    steps:
      - name: Install gpg & rpm
        run: apt-get update && apt-get install -y gpg rpm

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.pkg_type }}-${{ inputs.arch }}

      - name: Sign
        env:
          PYTHONUNBUFFERED: 1
          GPG_KEY_B64: ${{ secrets.GPG_KEY_B64 }}
          GPG_KEY_PASS_B64: ${{ secrets.GPG_KEY_PASS_B64 }}
        run: |
          if [ "${{ inputs.pkg_type }}" = "rpm" ]; then
            for i in $(find . -maxdepth 1 -type f -name "rippled-[0-9]*.rpm"); do
              echo "found $i"
              ./pkgs/sign_packages.py "$i"
            done
          elif [ "${{ inputs.pkg_type }}" = "deb" ]; then
            for i in $(find . -maxdepth 1 -type f -name "rippled_*.deb"); do
              echo "found $i"
              ./pkgs/sign_packages.py "$i"
            done
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: signed-rippled-${{ inputs.pkg_type }}-${{ inputs.arch }}
          path: |
            *.deb
            *.ddeb
          if-no-files-found: error
        if: inputs.pkg_type == 'deb'

      - uses: actions/upload-artifact@v4
        with:
          name: signed-rippled-${{ inputs.pkg_type }}-${{ inputs.arch }}
          path: "*${{ inputs.arch }}.${{ inputs.pkg_type }}"
          if-no-files-found: error
        if: inputs.pkg_type == 'rpm'

  docker:
    name: Build Docker image
    if: inputs.pkg_type == 'deb'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - uses: actions/download-artifact@v4
        with:
          name: deb-${{ inputs.arch }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/rippled
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: pkgs/docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
